# Generated by Django 5.1.3 on 2025-02-18 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField(blank=True, null=True)),
                ('score_b', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendent', 'Pendent'), ('in_course', 'In Course'), ('finished', 'Finished')], default='pendent', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(choices=[('league', 'League'), ('group', 'Group'), ('qualifiers', 'Qualifiers')], max_length=255)),
                ('members_per_team', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pendent', 'Pendent'), ('in_course', 'In Course'), ('finished', 'Finished')], default='pendent', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.modality')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('games', models.ManyToManyField(blank=True, to='competitions.game')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pontuation', models.IntegerField(blank=True, default=0)),
                ('register_date', models.DateField()),
                ('status', models.CharField(choices=[('pendent', 'Pendent'), ('approved', 'Approved')], default='pendent', max_length=255)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('approve_team', 'Approve Team'), ('delete_team', 'Delete Team'), ('remove_team_member', 'Remove Team Member')], max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendent', 'Pendent'), ('done', 'Done')], default='pendent', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='competitions.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='competitions.team'),
        ),
        migrations.CreateModel(
            name='Clasification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victories', models.IntegerField(default=0)),
                ('defeats', models.IntegerField(default=0)),
                ('ties', models.IntegerField(blank=True, default=0)),
                ('pontuation', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('points_pro', models.IntegerField(default=0)),
                ('points_against', models.IntegerField(default=0)),
                ('position', models.IntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competitions.team')),
            ],
        ),
    ]
