# Generated by Django 5.1.3 on 2025-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_rename_members_per_team_competition_min_members_per_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(default='PRZ', max_length=3),
            preserve_default=False,
        ),
    ]
