# Generated by Django 5.1.3 on 2025-02-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasification',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
