# Generated by Django 5.1.3 on 2025-02-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reason_rejected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pendent', 'Pendent'), ('done', 'Done'), ('rejected', 'Rejected')], default='pendent', max_length=255),
        ),
    ]
