# Generated by Django 5.1.3 on 2025-02-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_request_reason_rejected_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('approve_team', 'Aprovar equipe'), ('delete_team', 'Excluir equipe'), ('remove_team_member', 'Excluir participante')], max_length=255),
        ),
    ]
