# Generated by Django 5.1.3 on 2025-02-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_clasification_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='related_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.round'),
        ),
    ]
