# Generated by Django 5.1.3 on 2025-02-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_request_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pendent', 'Pendent'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pendent', max_length=255),
        ),
    ]
