# Generated by Django 5.1.3 on 2025-02-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_remove_round_games_game_related_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
