# Generated by Django 5.1.3 on 2025-02-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_game_date'),
        ('competitions', '0007_alter_request_status'),
    ]

    operations = [
    ]
