# Generated by Django 5.1.3 on 2025-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_merge_0007_alter_game_date_0007_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
